-- MySQL Script generated by MySQL Workbench
-- jue 23 ene 2020 22:32:23 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NOT NULL,
  `pass` VARCHAR(50) NOT NULL,
  `cash` DECIMAL(11,2) NOT NULL DEFAULT 100,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);

INSERT INTO user (username, pass) VALUES
  ('test', 'test'),
  ('test1', 'test'),
  ('test2', 'test'),
  ('test3', 'test'),
  ('test4', 'test'),
  ('test5', 'test');


-- -----------------------------------------------------
-- Table `ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(11,2) NOT NULL,
  `image` VARCHAR(100) NULL,
  PRIMARY KEY (`id`));

INSERT INTO product (name, price, image) VALUES
  ('Apple', 0.3, 'apple.jpg'),
  ('Beer', 2.0, 'beer.jpg'),
  ('Water', 1.0, 'water.jpg'),
  ('Cheese', 3.74, 'cheese.jpeg');


-- -----------------------------------------------------
-- Table `ecommerce`.`transport_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`transport_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(11,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));

INSERT INTO transport_type (name, price) VALUES
  ('pick up', 0),
  ('UPS', 5);


-- -----------------------------------------------------
-- Table `ecommerce`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transport_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_transport_idx` (`transport_id` ASC) VISIBLE,
  INDEX `fk_purchase_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_transport`
    FOREIGN KEY (`transport_id`)
    REFERENCES `ecommerce`.`transport_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecommerce`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `purchase_id` INT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_cart_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_cart_purchase_idx` (`purchase_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_purchase`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `ecommerce`.`purchase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `ecommerce`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`rate` (
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `rate` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`user_id`, `product_id`),
  INDEX `fk_rate_product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_rate_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecommerce`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rate_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `ecommerce`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
