version: '3'

services:
  app:
    build: .
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/dump.sql
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=True